### PR TITLE
(enh) add blue screen for WASM Runtime errors

### LINKED ISSUE #245: Add blue screen of death for WASM crashes
When there is a known common WASM crash, we should indicate it visibly.  Memory out of bounds errors seem to be quite common in my development so far.  If there were other common ones we could handle those as well.  I'm happy to work on this if we could agree on wording and visual style.

Mockup

Screen Shot 2021-12-26 at 4 05 40 PM
:

### PR DESCRIPTION
**Pull request by joshgoebel**
Adds blue screen error handling for common WASM Runtime errors.

Resolves #245 

- [x] web runtime
- [x] <del>native runtime</del> not necessary per @aduros 

Screen Shot 2021-12-27 at 8 35 10 AM
Screen Shot 2021-12-27 at 9 07 01 AM

### CODE REVIEW

File: runtimes/web/src/index.js [hunk 1]
```diff
@@ -473,7 +473,9 @@ async function loadCartWasm () {
 
         if (deltaFrame >= INTERVAL) {
             lastFrame = now - (deltaFrame % INTERVAL);
-            runtime.update();
+            if (!runtime.crashed) {
+                runtime.update();
+            }
```
Comment (joshgoebel) [inline runtimes/web/src/index.js:478]: This doesn't actually STOP the requestAnimation loop, but I think that's ok since it essentially turns it into just a NOP.

**Comment by joshgoebel** [comment]
Let me know how this looks and if it's good I can see about the native runtime.

File: runtimes/web/src/runtime.js [hunk 2]
```diff
@@ -289,12 +291,71 @@ export class Runtime {
...
+            message = "This cartridge has\nattempted a memory\naccess that is\nout of bounds.";
+        }
+        message += "\n\n\n\n\nHit R to reboot.";
+        return message;
+    }
+
+    blueScreen(err) {
+        this.crashed = true;
+
+        const COLORS = [
```
Comment (joshgoebel) [inline runtimes/web/src/runtime.js:326]: I could move this into `config` as CRASH_PALETTE also...

**Comment by aduros** [comment]
Thanks, I'll take a look!

Let's implement this for the web runtime only. On native we can just crash and print something to stdout.

**Comment by joshgoebel** [comment]
> Let's implement this for the web runtime only.

Sweet! No argument here!

**Comment by aduros** [comment]
Thanks!
